version: '3.7'

services:
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana-infinity-datasource
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-infinity-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment: 
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true