name: Pull Requests - Backend
on:
  pull_request:
    paths:
      - '**.go'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Lint backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v lint
      - name: Test backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: coverage
      - name: Build backend
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: buildAll